version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=ericwang
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=survey-db
    command: -c fsync=off -c full_page_writes=off -c synchronous_commit=off -c max_connections=500
    ports:
      - 10002:5432